#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;

public class CardGenerator
{
    [MenuItem("GoT Oyun Araçları/Tüm Hanedan Kartlarını Üret")]
    public static void Uret()
    {
        string baseFolder = "Assets/Cards/AutoGenerated";
        if (!AssetDatabase.IsValidFolder("Assets/Cards")) AssetDatabase.CreateFolder("Assets", "Cards");
        if (!AssetDatabase.IsValidFolder(baseFolder)) AssetDatabase.CreateFolder("Assets/Cards", "AutoGenerated");

        string starkFolder = baseFolder + "/Stark";
        if (!AssetDatabase.IsValidFolder(starkFolder)) AssetDatabase.CreateFolder(baseFolder, "Stark");

        string lannisterFolder = baseFolder + "/Lannister";
        if (!AssetDatabase.IsValidFolder(lannisterFolder)) AssetDatabase.CreateFolder(baseFolder, "Lannister");

        // ================= STARK KARTLARI =================
        // Başlangıç
        CreateCard(starkFolder, "Stark_Intikal", "İntikal", KartTuru.Aninda, "1 İntikal Puanı kazan. (İntikal puanları tur sonu silinmez).", 1, 0, 0, 0, 0, 0, 0, 1);
        CreateOrduKarti(starkFolder, "Stark_MilisEgit", "Milis Eğit", "Sınırların içindeki bir altıgende 1 Piyade birliği oluştur.", 1, 0, 0, 5, "Piyade");
        CreateBinaKarti(starkFolder, "Stark_SinirGenislet", "Sınır Genişlet", "Sınırlarını seçtiğin yönde 1 altıgen genişlet.", 1, 0, 3, 0, "Koy");
        CreateCard(starkFolder, "Stark_Hasat", "Hasat", KartTuru.Aninda, "3 Yemek kazan.", 3, 0, 0, 0, 0, 0, 3, 0, true, false, false, true);
        CreateCard(starkFolder, "Stark_Calis", "Çalış (Taş Ocağı)", KartTuru.Aninda, "3 Taş kazan.", 3, 0, 0, 0, 0, 3, 0, 0, true, false, true, false);
        CreateCard(starkFolder, "Stark_Vergi", "Vergi Topla", KartTuru.Aninda, "3 Altın kazan.", 3, 0, 0, 0, 3, 0, 0, 0, true, true, false, false);
        CreateCard(starkFolder, "Stark_Ulaklar", "Kuzeyin Ulakları", KartTuru.Aninda, "2 Kart çek ve 1 Taş kazan.", 1, 0, 0, 0, 0, 1, 0, 0, false, false, false, false, false, 2);
        
        // Stark Buff (Hedefli)
        CardData cesaretlen = CreateCard(starkFolder, "Stark_Cesaretlen", "Cesaretlen", KartTuru.Hedefli, "Seçili ordudaki tüm birimlerin hasarını kalıcı olarak 1 artır.", 1, 0, 0, 0);
        cesaretlen.orduHasarArtisi = 1;

        CardData yikilmaz = CreateCard(starkFolder, "Stark_Yikilmaz", "Yıkılmaz", KartTuru.Hedefli, "Seçili kalenin canını (HP) kalıcı olarak 1 artır.", 1, 0, 0, 0);
        yikilmaz.kaleKapiCaniArtisi = 1;

        // Stark Build 1
        CardData iyiles = CreateCard(starkFolder, "Stark_Iyiles", "İyileş", KartTuru.Hedefli, "Bir ordunun tüm yaşayan birliklerinin canını 1 artır.", 1, 0, 0, 0);
        iyiles.orduCanArtisi = 1;

        CardData atlar = CreateCard(starkFolder, "Stark_Atlar", "Atlar", KartTuru.Hedefli, "Bir ordunun hareket hızını kalıcı olarak 1 artır. (Tüket)", 1, 0, 0, 0, 0,0,0,0, false, false, false, false, true);
        atlar.orduHareketHiziArtisi = 1;

        CardData ileri = CreateCard(starkFolder, "Stark_Ileri", "İleri!", KartTuru.Hedefli, "Bir ordu seç. İntikal puanı harcamadan fazladan hareket etme hakkı kazanır.", 2, 0, 0, 0);
        ileri.ekHareketHakki = 2;

        CardData ziyafet = CreateCard(starkFolder, "Stark_Ziyafet", "Ziyafet", KartTuru.Hedefli, "Bir ordunun canını 1 artır. (Şartlı efektler arka planda çalışır)", 2, 0, 0, 0);
        ziyafet.orduCanArtisi = 1;

        // ================= LANNISTER KARTLARI =================
        // Başlangıç
        CreateCard(lannisterFolder, "Lannister_Intikal", "İntikal", KartTuru.Aninda, "1 İntikal Puanı kazan.", 1, 0, 0, 0, 0, 0, 0, 1);
        CreateOrduKarti(lannisterFolder, "Lannister_MilisEgit", "Milis Eğit", "Sınırların içindeki bir altıgende 1 Piyade birliği oluştur.", 1, 0, 0, 5, "Piyade");
        CreateBinaKarti(lannisterFolder, "Lannister_SinirGenislet", "Sınır Genişlet", "Sınırlarını seçtiğin yönde 1 altıgen genişlet.", 1, 0, 3, 0, "Koy");
        CreateCard(lannisterFolder, "Lannister_Hasat", "Hasat", KartTuru.Aninda, "3 Yemek kazan.", 3, 0, 0, 0, 0, 0, 3, 0, true, false, false, true);
        CreateCard(lannisterFolder, "Lannister_Calis", "Çalış (Taş Ocağı)", KartTuru.Aninda, "3 Taş kazan.", 3, 0, 0, 0, 0, 3, 0, 0, true, false, true, false);
        CreateCard(lannisterFolder, "Lannister_Vergi", "Vergi Topla", KartTuru.Aninda, "3 Altın kazan.", 3, 0, 0, 0, 3, 0, 0, 0, true, true, false, false);
        CreateCard(lannisterFolder, "Lannister_AltinMurekkep", "Altın Mürekkep", KartTuru.Aninda, "2 Kart çek ve 1 Altın kazan.", 1, 0, 0, 0, 1, 0, 0, 0, false, false, false, false, false, 2);

        // Lannister Sabotaj
        CardData paraninGucu = CreateCard(lannisterFolder, "Lannister_ParaninGucu", "Paranın Gücü", KartTuru.Hedefli, "Seçili düşman ordusunun bu tur hareket etmesini engelle.", 1, 0, 0, 0);
        paraninGucu.dusmanHareketEngelle = true;

        CardData rusvet = CreateCard(lannisterFolder, "Lannister_Rusvet", "Rüşvet", KartTuru.Hedefli, "Seçili bir düşman ordusunun içindeki 1 birimi yok et.", 1, 5, 0, 0);
        rusvet.dusmanBirlikYokEt = 1;

        CardData tedarikKes = CreateCard(lannisterFolder, "Lannister_TedarikKes", "Tedarik Hatlarını Kes", KartTuru.Hedefli, "Seçili düşman ordusunun tüm İntikal Puanlarını sıfırla.", 1, 4, 0, 0);
        tedarikKes.dusmanIntikalSifirla = true;

        CardData tarafDegistir = CreateCard(lannisterFolder, "Lannister_TarafDegistir", "Taraf Değiştir", KartTuru.Hedefli, "Zayıflamış bir düşman ordusunu anında kendi safına çek. (Tüket)", 2, 12, 0, 0, 0,0,0,0, false, false, false, false, true);
        tarafDegistir.dusmanOrduyuCal = true;

        // Lannister Ekonomi / Harita
        CardData acimasizEmirler = CreateCard(lannisterFolder, "Lannister_AcimasizEmirler", "Acımasız Emirler", KartTuru.Hedefli, "Kendi ordunu yok et. Karşılığında 6 Altın ve 2 kart kazan.", 0, 0, 0, 0, 6, 0, 0, 0, false, false, false, false, false, 2);
        acimasizEmirler.kendiOrdunuFedaEt = true;

        CardData zorlaTahsilat = CreateCard(lannisterFolder, "Lannister_ZorlaTahsilat", "Zorla Tahsilat", KartTuru.Aninda, "Kendi ordunu köyde hareket ettirerek altın kazanırsın.", 1, 0, 0, 0);
        zorlaTahsilat.zorlaTahsilatEfekti = true;

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log("SÜPER! Tüm Stark ve Lannister kartları Assets/Cards/AutoGenerated klasörü içine üretildi!");
    }

    private static CardData CreateCard(string path, string assetName, string displayName, KartTuru tur, string aciklama, 
        int ap, int altinB, int tasB, int yemekB, 
        int kazanAltin = 0, int kazanTas = 0, int kazanYemek = 0, int kazanIntikal = 0,
        bool sinirToprakEtkisi = false, bool sinirAltin = false, bool sinirTas = false, bool sinirYemek = false,
        bool isTuketim = false, int cekKart = 0)
    {
        CardData card = ScriptableObject.CreateInstance<CardData>();
        card.kartAdi = displayName;
        card.tur = tur;
        card.aciklama = aciklama;
        card.apBedeli = ap;
        card.altinBedeli = altinB;
        card.tasBedeli = tasB;
        card.yemekBedeli = yemekB;
        card.kazanilanAltin = kazanAltin;
        card.kazanilanTas = kazanTas;
        card.kazanilanYemek = kazanYemek;
        card.kazanilanIntikal = kazanIntikal;

        card.sinirdanAltinKazan = sinirAltin;
        card.sinirdanTasKazan = sinirTas;
        card.sinirdanYemekKazan = sinirYemek;
        
        card.isTuketimKarti = isTuketim;
        card.cekilecekKartSayisi = cekKart;

        AssetDatabase.CreateAsset(card, path + "/" + assetName + ".asset");
        return card;
    }

    private static CardData CreateOrduKarti(string path, string assetName, string displayName, string aciklama, int ap, int altinB, int tasB, int yemekB, string birlikAdi)
    {
        CardData card = CreateCard(path, assetName, displayName, KartTuru.Hedefli, aciklama, ap, altinB, tasB, yemekB);
        card.orduKartiMi = true;
        card.uretilecekBirlikler.Add(birlikAdi);
        return card;
    }

    private static CardData CreateBinaKarti(string path, string assetName, string displayName, string aciklama, int ap, int altinB, int tasB, int yemekB, string binaAdi)
    {
        CardData card = CreateCard(path, assetName, displayName, KartTuru.Hedefli, aciklama, ap, altinB, tasB, yemekB);
        card.binaKartiMi = true;
        card.insaEdilecekBina = binaAdi;
        return card;
    }
}
#endif
